version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  build-artifact:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  lint-code:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
  check-typescript:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run ts            
  run-tests-unit:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test:unit
            - store_test_results:
                path: ./test-results
            - store_artifacts:
                path: ./test-results
  run-tests-e2e:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test:e2e
            - store_test_results:
                path: ./test-results
            - store_artifacts:
                path: ./test-results
  deploy-to-uat:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/vercel -c -t ${NOW_TOKEN}
  deploy-to-prd:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/vercel -c -t ${NOW_TOKEN} --prod

workflows:
    build-test-and-deploy:
      jobs:
        - build-artifact
        - run-tests-e2e:
            requires:
              - build-artifact        
        - lint-code:
            requires:
              - build-artifact
        - check-typescript:
            requires:
              - build-artifact
        - run-tests-unit:
            requires:
              - lint-code
              - check-typescript
        - deploy-to-uat:
            requires:
              - run-tests-unit
        # - cypress/run:
        #     requires:
        #       - deploy-to-uat
        - approve-uat:
            type: approval
            requires:
              - cypress/run
        - deploy-to-prd:
            requires:
              - approve-uat
