version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
  deploy:
    commands:
      - now -t ${NOW_TOKEN}

workflows:
    build-and-test-and-deploy:
      jobs:
        - build
        - test
        - deploy