version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  build-artifact:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  lint-code:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
  check-typescript:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run ts            
  run-tests-unit:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test:unit
  # run-tests-e2e:
  #   executor:
  #     name: cypress/run
  #   steps:
  #     - checkout
  #     - cypress/run:
  #         steps:
  #           - run: npm run test:e2e
  deploy-to-uat:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/vercel -c -t ${NOW_TOKEN}
  deploy-to-prd:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/vercel -c -t ${NOW_TOKEN} --prod

workflows:
    # build:
    #   jobs:
    #     - cypress/run 
    build-test-and-deploy:
      jobs:
        - build-artifact
        - cypress/run:
            requires:
              - build-artifact
        - lint-code:
            requires:
              - build-artifact
        - check-typescript:
            requires:
              - build-artifact
        - run-tests-unit:
            requires:
              - lint-code
              - check-typescript
        - deploy-to-uat:
            requires:
              - run-tests-unit
              # - run-tests-e2e             
        # - run-tests-e2e:
        #     requires:
        #       - lint-code
        #       - check-typescript
        - approve-uat:
            type: approval
            requires:
              - deploy-to-uat
        - deploy-to-prd:
            requires:
              - approve-uat
