version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    description: Build artifact
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
    description: Run tests
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
            - run: npm run ts
            - run: npm run test
  deploy-uat:
    description: Deploy to User Acceptance Testing
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/now -c -t ${NOW_TOKEN}
  deploy-prd:
    description: Deploy to Production
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/now -c -t ${NOW_TOKEN} --prod

workflows:
    build-test-and-deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy-uat:
            requires:
              - test
        - approve-prd:
            type: approval
            requires:
              - deploy-uat
        - deploy-prd:
            requires:
              - approve-prd