version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-artifact:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  lint-code:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
  check-typescript:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run ts            
  run-unit-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test
  deploy-to-uat:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/now -c -t ${NOW_TOKEN}
  deploy-to-prd:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/now -c -t ${NOW_TOKEN} --prod

workflows:
    build-test-and-deploy:
      jobs:
        - build-artifact
        - lint-code:
            requires:
              - build-artifact
        - check-typescript:
            requires:
              - build-artifact
        - run-unit-tests:
            requires:
              - lint-code
              - check-typescript
        - deploy-to-uat:
            requires:
              - run-unit-tests
        - approve-uat:
            type: approval
            requires:
              - deploy-to-uat
        - deploy-to-prd:
            requires:
              - approve-uat