version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
            - run: npm run ts
            - run: npm run test
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./node_modules/.bin/now -c -t ${NOW_TOKEN}

workflows:
    build-test-and-deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - build
            #   - test